development:
  adapter: postgresql
  encoding: unicode
  database: lunchcounter
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: lunchcounter
  pool: 5
  timeout: 5000